name = "cloudflare-homepage-api"
main = "dist/worker/index.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
watch_dir = "src"

# CORS 配置
[vars]
ALLOWED_ORIGINS = "https://cloudflare-homepage.pages.dev"
ADMIN_PASSWORD = "your-secure-password"

[[kv_namespaces]]
binding = "PORTFOLIO_KV"
id = "79db7536a2b546c8ad7f457e647b030d"

[[d1_databases]]
binding = "DB"
database_name = "portfolio_db"
database_id = "d747fc3c-4d76-4fdc-b367-572be080d726"